using Carves.Runtime.Application.Artifacts;
using Carves.Runtime.Application.AI;
using Carves.Runtime.Application.CodeGraph;
using Carves.Runtime.Application.Configuration;
using Carves.Runtime.Application.ControlPlane;
using Carves.Runtime.Application.Failures;
using Carves.Runtime.Application.Interaction;
using Carves.Runtime.Application.Memory;
using Carves.Runtime.Application.Orchestration;
using Carves.Runtime.Application.Platform;
using Carves.Runtime.Application.Planning;
using Carves.Runtime.Application.Refactoring;
using Carves.Runtime.Application.Safety;
using Carves.Runtime.Application.TaskGraph;
using Carves.Runtime.Application.Workers;

namespace Carves.Runtime.Host;

public static partial class RuntimeComposition
{
    private static RuntimeServices BuildRuntimeServices(
        RuntimeBootstrapContext bootstrap,
        RuntimeInfrastructureServices infrastructure,
        TaskGraphService taskGraphService,
        PlannerService plannerService,
        ICodeGraphQueryService codeGraphQueryService,
        InteractionLayerService interactionLayerService,
        IntentDiscoveryService intentDiscoveryService,
        PlanningDraftService planningDraftService,
        FormalPlanningPacketService formalPlanningPacketService,
        ManagedWorkspaceLeaseService managedWorkspaceLeaseService,
        ConversationProtocolService conversationProtocolService,
        PromptProtocolService promptProtocolService,
        PromptKernelService promptKernelService,
        ProjectUnderstandingProjectionService projectUnderstandingProjectionService,
        ApprovalPolicyEngine approvalPolicyEngine,
        WorkerPermissionOrchestrationService workerPermissionOrchestrationService,
        WorkerSelectionPolicyService workerSelectionPolicyService,
        WorkerRequestFactory workerRequestFactory,
        WorkerService workerService,
        SafetyService safetyService,
        DevLoopService devLoopService,
        IMarkdownSyncService markdownSyncService,
        FailureReportService failureReportService,
        FailureContextService failureContextService,
        FailureSummaryService failureSummaryService,
        PlannerTriggerService plannerTriggerService,
        DispatchProjectionService dispatchProjectionService,
        ExecutionRunService executionRunService,
        ResultIngestionService resultIngestionService,
        ICodeGraphBuilder codeGraphBuilder,
        IRefactoringService refactoringService,
        OperatorSurfaceService operatorSurfaceService,
        HostRegistryService hostRegistryService,
        RepoRegistryService repoRegistryService,
        RepoRuntimeService repoRuntimeService,
        RuntimeInstanceManager runtimeInstanceManager,
        ProviderRegistryService providerRegistryService,
        ProviderRoutingService providerRoutingService,
        RuntimeRoutingProfileService runtimeRoutingProfileService,
        CurrentModelQualificationService currentModelQualificationService,
        PlatformGovernanceService platformGovernanceService,
        PlatformSchedulerService platformSchedulerService,
        ActorSessionService actorSessionService,
        RuntimeSessionGatewayService runtimeSessionGatewayService,
        SessionOwnershipService sessionOwnershipService,
        ConcurrentActorArbitrationService concurrentActorArbitrationService,
        OperatorOsEventStreamService operatorOsEventStreamService,
        PlatformVocabularyLintService platformVocabularyLintService,
        OperatorApiService operatorApiService,
        PlatformDashboardService dashboardService,
        WorkbenchSurfaceService workbenchSurfaceService,
        WorkerBroker workerBroker,
        WorkerOperationalPolicyService workerOperationalPolicyService,
        RuntimePolicyBundleService runtimePolicyBundleService,
        ProviderHealthMonitorService providerHealthMonitorService,
        RuntimeConsistencyCheckService runtimeConsistencyCheckService,
        DelegatedWorkerLifecycleReconciliationService delegatedWorkerLifecycleReconciliationService,
        OperationalSummaryService operationalSummaryService,
        GovernanceReportingService governanceReportingService,
        DelegationReportingService delegationReportingService,
        WorktreeResourceCleanupService worktreeResourceCleanupService)
    {
        return new RuntimeServices(
            bootstrap.Paths,
            bootstrap.SystemConfig,
            bootstrap.AiProviderConfig,
            bootstrap.ConfigRepository,
            bootstrap.WorkerOperationalPolicy,
            taskGraphService,
            plannerService,
            codeGraphQueryService,
            interactionLayerService,
            intentDiscoveryService,
            planningDraftService,
            formalPlanningPacketService,
            managedWorkspaceLeaseService,
            conversationProtocolService,
            promptProtocolService,
            promptKernelService,
            projectUnderstandingProjectionService,
            infrastructure.GitClient,
            infrastructure.AiClient,
            infrastructure.PlannerAdapterRegistry,
            infrastructure.WorkerAdapterRegistry,
            approvalPolicyEngine,
            workerPermissionOrchestrationService,
            workerSelectionPolicyService,
            workerRequestFactory,
            workerService,
            safetyService,
            devLoopService,
            markdownSyncService,
            infrastructure.ArtifactRepository,
            failureReportService,
            failureContextService,
            failureSummaryService,
            plannerTriggerService,
            dispatchProjectionService,
            executionRunService,
            resultIngestionService,
            codeGraphBuilder,
            refactoringService,
            operatorSurfaceService,
            hostRegistryService,
            repoRegistryService,
            repoRuntimeService,
            runtimeInstanceManager,
            providerRegistryService,
            providerRoutingService,
            runtimeRoutingProfileService,
            currentModelQualificationService,
            platformGovernanceService,
            platformSchedulerService,
            actorSessionService,
            runtimeSessionGatewayService,
            sessionOwnershipService,
            concurrentActorArbitrationService,
            operatorOsEventStreamService,
            platformVocabularyLintService,
            operatorApiService,
            dashboardService,
            workbenchSurfaceService,
            workerBroker,
            workerOperationalPolicyService,
            runtimePolicyBundleService,
            providerHealthMonitorService,
            runtimeConsistencyCheckService,
            delegatedWorkerLifecycleReconciliationService,
            operationalSummaryService,
            governanceReportingService,
            delegationReportingService,
            worktreeResourceCleanupService);
    }
}
