using System.Text.Json;

namespace Carves.Handoff.Core;

public sealed class HandoffDraftService
{
    public const string DraftSchemaVersion = HandoffJsonContracts.DraftSchemaVersion;
    private readonly HandoffDraftPathPolicy pathPolicy;
    private readonly HandoffInspectionService inspectionService;

    public HandoffDraftService()
        : this(HandoffDraftPathPolicy.Default, new HandoffInspectionService())
    {
    }

    public HandoffDraftService(HandoffDraftPathPolicy pathPolicy, HandoffInspectionService inspectionService)
    {
        this.pathPolicy = pathPolicy;
        this.inspectionService = inspectionService;
    }

    public HandoffDraftResult Draft(string repoRoot, string packetPath)
    {
        if (string.IsNullOrWhiteSpace(packetPath))
        {
            return Failure(packetPath, "invalid_path", "draft.path_missing", "Packet path is required.");
        }

        string resolvedPath;
        string relativePath;
        try
        {
            var resolution = pathPolicy.Resolve(repoRoot, packetPath);
            resolvedPath = resolution.ResolvedPath;
            relativePath = resolution.RelativePath;
        }
        catch (InvalidOperationException exception)
        {
            return Failure(packetPath, "outside_repo", "draft.path_outside_repo", exception.Message);
        }
        catch (Exception exception) when (exception is ArgumentException or NotSupportedException or PathTooLongException)
        {
            return Failure(packetPath, "invalid_path", "draft.path_invalid", exception.Message);
        }

        if (Directory.Exists(resolvedPath) || string.IsNullOrWhiteSpace(Path.GetFileName(resolvedPath)))
        {
            return Failure(packetPath, "invalid_path", "draft.path_is_directory", "Packet path must point to a file.");
        }

        if (pathPolicy.IsProtectedPath(relativePath))
        {
            return Failure(packetPath, "protected_path", "draft.protected_path", "Packet path is protected for handoff draft output.");
        }

        if (File.Exists(resolvedPath))
        {
            return Failure(packetPath, "exists", "draft.target_exists", "Packet path already exists; draft refuses to overwrite.");
        }

        var handoffId = $"HND-DRAFT-{DateTimeOffset.UtcNow:yyyyMMddHHmmssfff}-{Guid.NewGuid():N}"[..43];
        var packet = BuildDraftPacket(repoRoot, handoffId);
        try
        {
            Directory.CreateDirectory(Path.GetDirectoryName(resolvedPath)!);
            File.WriteAllText(resolvedPath, JsonSerializer.Serialize(packet, HandoffJsonContracts.JsonOptions) + Environment.NewLine);
        }
        catch (Exception exception) when (exception is UnauthorizedAccessException or IOException)
        {
            return Failure(packetPath, "write_failed", "draft.write_failed", exception.Message);
        }

        var inspection = inspectionService.Inspect(repoRoot, packetPath);
        return new HandoffDraftResult(
            DraftSchemaVersion,
            packetPath,
            handoffId,
            "written",
            Written: true,
            inspection,
            []);
    }

    private static HandoffDraftPacket BuildDraftPacket(string repoRoot, string handoffId)
    {
        return new HandoffDraftPacket(
            HandoffInspectionService.SupportedPacketSchemaVersion,
            handoffId,
            DateTimeOffset.UtcNow.ToString("O"),
            new HandoffDraftProducer("carves", null),
            new HandoffDraftRepo(new DirectoryInfo(repoRoot).Name, ".", "unknown", "unknown", "unknown"),
            "operator_review_required",
            "TODO: replace with the bounded objective being handed off.",
            new HandoffDraftCursor("manual", "TODO", "TODO: replace with the current cursor.", "unknown", []),
            [],
            [new HandoffDraftRemainingWork("Replace this draft skeleton with evidence-backed handoff details.", [], [])],
            [],
            [],
            [new HandoffDraftOpenQuestion("Has the operator reviewed and completed this draft packet?", "operator", "Blocks using this packet as an incoming-agent resume guide.")],
            [],
            [],
            [],
            new HandoffDraftNextAction(
                "Complete this draft with bounded context refs and evidence-backed facts, then run carves-handoff inspect --json.",
                "Draft packets are low confidence until inspected and reviewed."),
            "low",
            [
                "Generated by carves-handoff draft.",
                "repo.root_hint is a local-only hint and is not portable repository truth.",
                "This skeleton is intentionally operator_review_required and low confidence.",
                "Do not treat this packet as ready until it is completed and inspected."
            ]);
    }

    private static HandoffDraftResult Failure(string packetPath, string status, string code, string message)
    {
        return new HandoffDraftResult(
            DraftSchemaVersion,
            packetPath,
            null,
            status,
            Written: false,
            null,
            [new HandoffInspectionDiagnostic(code, "error", message)]);
    }
}

public sealed record HandoffDraftResult(
    string SchemaVersion,
    string PacketPath,
    string? HandoffId,
    string DraftStatus,
    bool Written,
    HandoffInspectionResult? Inspection,
    IReadOnlyList<HandoffInspectionDiagnostic> Diagnostics);

internal sealed record HandoffDraftPacket(
    string SchemaVersion,
    string HandoffId,
    string CreatedAtUtc,
    HandoffDraftProducer Producer,
    HandoffDraftRepo Repo,
    string ResumeStatus,
    string CurrentObjective,
    HandoffDraftCursor CurrentCursor,
    IReadOnlyList<object> CompletedFacts,
    IReadOnlyList<HandoffDraftRemainingWork> RemainingWork,
    IReadOnlyList<object> BlockedReasons,
    IReadOnlyList<object> MustNotRepeat,
    IReadOnlyList<HandoffDraftOpenQuestion> OpenQuestions,
    IReadOnlyList<object> DecisionRefs,
    IReadOnlyList<object> EvidenceRefs,
    IReadOnlyList<object> ContextRefs,
    HandoffDraftNextAction RecommendedNextAction,
    string Confidence,
    IReadOnlyList<string> ConfidenceNotes);

internal sealed record HandoffDraftProducer(string Agent, string? SessionId);

internal sealed record HandoffDraftRepo(
    string Name,
    string RootHint,
    string Branch,
    string BaseCommit,
    string DirtyState);

internal sealed record HandoffDraftCursor(
    string Kind,
    string Id,
    string Title,
    string Status,
    IReadOnlyList<string> Scope);

internal sealed record HandoffDraftRemainingWork(
    string Action,
    IReadOnlyList<string> Scope,
    IReadOnlyList<string> BlockedBy);

internal sealed record HandoffDraftOpenQuestion(string Question, string NeededFrom, string Impact);

internal sealed record HandoffDraftNextAction(string Action, string Rationale);
