namespace Carves.Runtime.Application.Configuration;

public sealed record CarvesAuthorityRules(
    IReadOnlyList<string> RecorderWritableBy,
    IReadOnlyList<string> DomainEventsEmittedBy,
    bool ViewReadOnly,
    bool ControllerDirectRecorderWriteForbidden,
    bool ActorDirectRecorderWriteForbidden);

public sealed record CarvesApplicabilityRules(
    string CarvesPurpose,
    string RuntimePurpose,
    bool DirectoryLayoutRequired,
    bool OneClassPerLayerRequired,
    bool RefactorForPurityAloneForbidden);

public sealed record CarvesAiFriendlyArchitectureRules(
    string CorePrinciple,
    bool DomainOrientedLayoutPreferred,
    bool AvoidGenericDirectories,
    bool AvoidGenericTypeNames,
    bool InterfacesOnlyAtRealBoundaries,
    bool ExplicitStateModelingRequired,
    int RecommendedFileLinesLowerBound,
    int RecommendedFileLinesUpperBound,
    int RefactorFileLinesThreshold,
    int MaxConceptualJumps);

public sealed record CarvesPhysicalSplittingRules(
    string CorePrinciple,
    bool LogicalLayersStrict,
    bool PhysicalSplittingElastic,
    int SplitScoreCanSplit,
    int SplitScoreShouldSplit,
    bool AvoidThinForwarderSplits,
    bool AvoidCompletenessSplits,
    bool SharedOnlyForNonSovereignSupport,
    IReadOnlyList<string> RuntimeRecommendedIndependentModules);

public sealed record CarvesExtremeNamingRules(
    string CorePrinciple,
    string NamingGrammar,
    bool DomainMustLead,
    bool RoleSuffixMustBeTerminal,
    bool FullWordsRequired,
    bool PascalCaseRequired,
    bool FileNameMatchesPrimaryType,
    bool OneConceptOneHeadword,
    bool CanonicalVocabularyRequired,
    bool ApplicationServiceRequiresCompatibilityAnnotation,
    bool EngineSystemLevelOnly,
    IReadOnlyList<string> CanonicalArchitecturalTerms,
    IReadOnlyList<string> CanonicalExecuteTerms,
    IReadOnlyList<string> CanonicalRuntimeTerms,
    IReadOnlyList<string> CanonicalPlatformTerms,
    IReadOnlyList<string> CanonicalMechanismTerms,
    IReadOnlyList<string> ForbiddenGenericWords,
    IReadOnlyList<string> SuggestedAnalyzerRules,
    IReadOnlyDictionary<string, string> PlatformForbiddenAliases,
    IReadOnlyList<string> PlatformLintPaths,
    IReadOnlyList<string> PlatformLintAllowlistTypeNames);

public sealed record CarvesDependencyContractRules(
    string CorePrinciple,
    bool DependencyDirectionOneWay,
    bool SameLayerCouplingRestricted,
    IReadOnlyList<string> RoleClassificationPrecedence,
    IReadOnlyList<string> IncludedEdgeKinds,
    IReadOnlyList<string> ExcludedEdgeKinds,
    string RecorderAccessModel,
    string AmbiguousSymbolPolicy,
    IReadOnlyDictionary<string, IReadOnlyList<string>> AllowedDependencyMatrix,
    IReadOnlyList<string> ForbiddenDiagnosticRules,
    IReadOnlyList<string> RestrictedDiagnosticRules,
    IReadOnlyList<string> AdvisoryDiagnosticRules);

public sealed record CarvesCodeStandard(
    string Version,
    string CoreLoop,
    string InteractionLoop,
    CarvesAuthorityRules Authority,
    CarvesApplicabilityRules Applicability,
    CarvesAiFriendlyArchitectureRules AiFriendlyArchitecture,
    CarvesPhysicalSplittingRules PhysicalSplitting,
    CarvesExtremeNamingRules ExtremeNaming,
    CarvesDependencyContractRules DependencyContract,
    IReadOnlyList<string> AllowedEdges,
    IReadOnlyList<string> RestrictedEdges,
    IReadOnlyList<string> ForbiddenEdges,
    IReadOnlyList<string> ModerationRules,
    IReadOnlyList<string> ReviewQuestions,
    IReadOnlyList<string> RuntimeQuestions)
{
    public static CarvesCodeStandard CreateDefault()
    {
        return new CarvesCodeStandard(
            "0.4",
            "Controller -> Execute -> Actor / Service -> Recorder -> View",
            "View -> Controller -> Execute -> Recorder -> View",
            new CarvesAuthorityRules(
                ["Execute"],
                ["Recorder"],
                true,
                true,
                true),
            new CarvesApplicabilityRules(
                "CARVES constrains generated or modified product code.",
                "CARVES.Runtime governs AI planning, execution, safety, and review for that code.",
                false,
                false,
                true),
            new CarvesAiFriendlyArchitectureRules(
                "Code structure must adapt to AI reasoning constraints. AI intelligence must not be relied upon to compensate for poor structure.",
                true,
                true,
                true,
                true,
                true,
                200,
                500,
                800,
                5),
            new CarvesPhysicalSplittingRules(
                "Logical boundaries stay strict while physical splitting remains elastic.",
                true,
                true,
                3,
                4,
                true,
                true,
                true,
                [
                    "TaskTransitionPolicy",
                    "RuntimeFailurePolicy",
                    "TaskConflictDetector",
                    "TaskConcurrencyPolicy",
                    "ControlPlaneLockService",
                    "PlannerReviewArtifactFactory",
                ]),
            new CarvesExtremeNamingRules(
                "Naming is an architecture contract for AI-readable codebases, not a style preference.",
                "<Domain><Qualifier?><RoleSuffix>",
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                true,
                [
                    "Controller",
                    "Actor",
                    "Recorder",
                    "View",
                    "Execute",
                    "Shared",
                ],
                [
                    "Procedure",
                    "Module",
                    "Service",
                ],
                [
                    "Planner",
                    "Scheduler",
                    "Worker",
                    "Pipeline",
                    "Broker",
                    "Registry",
                    "Instance",
                    "Lease",
                    "Quota",
                    "Pool",
                    "Detector",
                    "Evaluator",
                    "Opportunity",
                    "Admission",
                ],
                [
                    "Registry",
                    "Instance",
                    "Broker",
                    "Gateway",
                    "Lease",
                    "Quota",
                    "Policy",
                    "Event",
                    "Dashboard",
                    "OperatorApi",
                    "Node",
                    "Provider",
                    "Fabric",
                ],
                [
                    "Command",
                    "Query",
                    "Request",
                    "Response",
                    "State",
                    "Status",
                    "Phase",
                    "Reason",
                    "Actionability",
                    "Snapshot",
                    "Record",
                    "Manifest",
                    "Ledger",
                    "Decision",
                    "Outcome",
                    "Result",
                    "Policy",
                    "Strategy",
                    "Rule",
                    "Validator",
                    "Guard",
                    "Check",
                    "Context",
                    "Scope",
                    "Boundary",
                    "Allocator",
                    "Resolver",
                    "Selector",
                    "Mapper",
                    "Adapter",
                    "Factory",
                    "Serializer",
                    "Deserializer",
                    "Dto",
                    "ViewModel",
                ],
                [
                    "Manager",
                    "Processor",
                    "Helper",
                    "Utils",
                    "Common",
                    "Logic",
                    "Thing",
                    "Info",
                    "Data",
                    "Item",
                    "Base",
                ],
                [
                    "CARVES001",
                    "CARVES002",
                    "CARVES003",
                    "CARVES004",
                    "CARVES005",
                    "CARVES006",
                    "CARVES007",
                    "CARVES008",
                    "CARVES009",
                    "CARVES010",
                    "CARVES101",
                    "CARVES102",
                    "CARVES103",
                    "CARVES104",
                    "CARVES105",
                    "CARVES106",
                    "CARVES107",
                    "CARVES108",
                    "CARVES201",
                    "CARVES202",
                    "CARVES203",
                    "CARVES204",
                    "CARVES205",
                    "CARVES301",
                    "CARVES302",
                    "CARVES303",
                    "CARVES304",
                    "CARVES305",
                ],
                new Dictionary<string, string>(StringComparer.Ordinal)
                {
                    ["Directory"] = "Registry",
                    ["Hub"] = "Broker",
                    ["Finder"] = "Detector",
                    ["Cause"] = "Reason",
                    ["Coordinator"] = "Scheduler",
                    ["Supervisor"] = "Broker",
                },
                [
                    "src/CARVES.Runtime.Domain/Platform",
                    "src/CARVES.Runtime.Application/Platform",
                    "src/CARVES.Runtime.Infrastructure/Platform",
                    "src/CARVES.Runtime.Host",
                ],
                [
                    "RuntimeInstanceManager",
                ]),
            new CarvesDependencyContractRules(
                "Dependency direction is architecture law: truth writes stay under Execute, reverse dependencies are forbidden, and same-layer coupling is restricted by default.",
                true,
                true,
                [
                    "attribute",
                    "namespace",
                    "directory",
                    "suffix",
                ],
                [
                    "constructor_parameter",
                    "field",
                    "property",
                    "method_invocation",
                    "object_creation",
                    "implemented_interface",
                    "base_type",
                ],
                [
                    "reflection_based",
                    "string_service_locator",
                    "source_generator_synthetic_wiring",
                    "di_container_registration_semantics",
                    "dynamic_dispatch_beyond_symbol_resolution",
                ],
                "split_reader_writer_ports_preferred",
                "emit_info_and_skip_strict_enforcement",
                new Dictionary<string, IReadOnlyList<string>>(StringComparer.Ordinal)
                {
                    ["Controller"] = ["Procedure", "Shared"],
                    ["View"] = ["Controller", "RecorderReader", "Shared"],
                    ["Procedure"] = ["Module", "Shared"],
                    ["Module"] = ["Service", "Actor", "RecorderWriter", "Shared"],
                    ["Service"] = ["Service", "Shared"],
                    ["Actor"] = ["Shared"],
                    ["Recorder"] = ["Shared"],
                    ["Shared"] = ["Shared"],
                },
                [
                    "CARVES101",
                    "CARVES102",
                    "CARVES103",
                    "CARVES104",
                    "CARVES105",
                    "CARVES106",
                    "CARVES107",
                    "CARVES108",
                    "CARVES109",
                ],
                [
                    "CARVES201",
                    "CARVES202",
                    "CARVES203",
                ],
                [
                    "CARVES100",
                    "CARVES301",
                    "CARVES302",
                    "CARVES303",
                ]),
            [
                "Controller -> Procedure",
                "Procedure -> Module",
                "Module -> Service",
                "Module -> Actor",
                "Module -> Recorder(write)",
                "View -> Controller",
                "View -> Recorder(read/subscribe)",
            ],
            [
                "Service -> Service only for pure capability reuse",
                "Module -> Module requires explicit architectural reason",
                "Procedure -> Procedure requires explicit higher-order coordination reason",
            ],
            [
                "Controller -> Recorder(write)",
                "View -> Recorder(write)",
                "Actor -> Recorder(write business truth directly)",
                "Service -> Module",
                "Service -> Procedure",
                "Module -> Procedure",
                "Recorder -> Execute(reverse call)",
                "View / Actor / Service / Module -> Publish domain events directly",
            ],
            [
                "Treat CARVES as the first interpretation layer, not as forced directory mirroring.",
                "Do not split trivial logic only to satisfy layer naming purity.",
                "Restricted edges require explicit reason and review, not automatic rejection.",
                "Legacy code may remain in place when the patch preserves Recorder authority and lowers risk.",
                "Do not apply CARVES layer mapping to CARVES.Runtime control-plane internals unless the task explicitly targets product code.",
            ],
            [
                "Which CARVES layer does this patch belong to?",
                "Where is the authoritative state after this change?",
                "Does the write path still remain Controller -> Execute -> Recorder?",
                "Are domain events still emitted only from Recorder?",
                "Does View still observe truth rather than creating truth?",
            ],
            [
                "Which CARVES layers does this runtime task affect in the target product code?",
                "Can Safety detect the boundary violation this patch would introduce?",
                "Does CodeGraph expose the likely layer impact of this change?",
                "Does this patch preserve Execute -> Recorder as the only business-truth write path?",
                "Is this change constraining product architecture or accidentally constraining control-plane implementation?",
            ]);
    }
}
