namespace Carves.Matrix.Core;

public static partial class MatrixCliRunner
{
    private static void WriteNativeFullReleaseReadyHandoffPacket(string packetPath, string guardRunId)
    {
        var handoffId = "HND-MATRIX-" + Guid.NewGuid().ToString("N")[..12].ToUpperInvariant();
        var createdAt = DateTimeOffset.UtcNow.ToString("O");
        var payload = $$"""
            {
              "schema_version": "carves-continuity-handoff.v1",
              "handoff_id": "{{handoffId}}",
              "created_at_utc": "{{createdAt}}",
              "producer": {
                "agent": "matrix-native-project-proof",
                "tool": "carves-handoff",
                "version": "local"
              },
              "repo": {
                "name": "external-target",
                "path_hint": ".",
                "branch": "main"
              },
              "resume_status": "ready",
              "current_objective": "Review the matrix smoke artifacts and keep the Guard decision linked to this handoff packet.",
              "current_cursor": {
                "kind": "guard-run",
                "id": "{{guardRunId}}"
              },
              "completed_facts": [
                {
                  "statement": "Guard produced a local diff-only decision for the matrix smoke patch.",
                  "evidence_refs": [
                    "guard-run:{{guardRunId}}",
                    ".ai/runtime/guard/decisions.jsonl"
                  ],
                  "confidence": "high"
                }
              ],
              "remaining_work": [
                {
                  "action": "Inspect Audit evidence and Shield evaluation outputs before publishing the matrix proof."
                }
              ],
              "blocked_reasons": [],
              "must_not_repeat": [
                {
                  "item": "Do not upload source code, raw diffs, prompts, model responses, secrets, credentials, or private payloads as proof artifacts.",
                  "reason": "The public matrix proof is summary-only and local-only."
                }
              ],
              "open_questions": [],
              "decision_refs": [
                "guard-run:{{guardRunId}}"
              ],
              "evidence_refs": [
                {
                  "kind": "guard",
                  "ref": "guard-run:{{guardRunId}}",
                  "summary": "Guard decision produced by the matrix smoke."
                }
              ],
              "context_refs": [
                {
                  "ref": ".ai/runtime/guard/decisions.jsonl",
                  "reason": "Append-only Guard decision readback for this matrix smoke.",
                  "priority": 1
                }
              ],
              "recommended_next_action": {
                "action": "Run carves-audit evidence and carves-shield evaluate.",
                "rationale": "Audit-generated shield-evidence.v0 is the stable Shield input."
              },
              "confidence": "medium",
              "confidence_notes": [
                "This packet is generated by the matrix native project proof after a real Guard decision is recorded."
              ]
            }
            """;
        var directory = Path.GetDirectoryName(packetPath);
        if (!string.IsNullOrWhiteSpace(directory))
        {
            Directory.CreateDirectory(directory);
        }

        File.WriteAllText(packetPath, payload);
    }
}
