using Carves.Runtime.Application.CodeGraph;
using Carves.Runtime.Application.Planning;
using Carves.Runtime.Application.TaskGraph;
using Carves.Runtime.Domain.Tasks;
using Carves.Runtime.Infrastructure.CodeGraph;
using DomainTaskGraph = Carves.Runtime.Domain.Tasks.TaskGraph;
using ApplicationTaskScheduler = Carves.Runtime.Application.TaskGraph.TaskScheduler;

namespace Carves.Runtime.Application.Tests;

public sealed class CodeGraphIntegrationTests
{
    [Fact]
    public void QueryService_AnalyzesReverseImpactFromPersistedCodeGraph()
    {
        using var workspace = new TemporaryWorkspace();
        workspace.WriteFile("src/Sample.Module/OrderService.cs", """
namespace Sample.Module;

public sealed class OrderService
{
    public void PlanOrder()
    {
    }
}
""");
        workspace.WriteFile("src/Sample.Consumer/OrderConsumer.cs", """
using Sample.Module;

namespace Sample.Consumer;

public sealed class OrderConsumer
{
    public void Consume(OrderService service)
    {
    }
}
""");

        var builder = new FileCodeGraphBuilder(workspace.RootPath, workspace.Paths, TestSystemConfigFactory.Create());
        var queryService = new FileCodeGraphQueryService(workspace.Paths, builder);
        builder.Build();

        var impact = queryService.AnalyzeImpact(["src/Sample.Module/"]);

        Assert.Contains("Sample.Consumer", impact.ImpactedModules);
        Assert.Contains("src/Sample.Consumer/OrderConsumer.cs", impact.ImpactedFiles);
    }

    [Fact]
    public void Planner_StoresImpactMetadataFromCodeGraph()
    {
        using var workspace = new TemporaryWorkspace();
        var cardPath = workspace.WriteFile(".ai/tasks/cards/CARD-IMPACT.md", """
# CARD-IMPACT
Title: Impact metadata
Type: feature
Priority: P1

## Goal
Capture impact metadata from codegraph.

## Scope
- `src/Sample.Module/`

## Acceptance
- planner records impact metadata
""");
        workspace.WriteFile("src/Sample.Module/OrderService.cs", """
namespace Sample.Module;

public sealed class OrderService
{
    public void PlanOrder()
    {
    }
}
""");
        workspace.WriteFile("src/Sample.Consumer/OrderConsumer.cs", """
using Sample.Module;

namespace Sample.Consumer;

public sealed class OrderConsumer
{
    public void Consume(OrderService service)
    {
    }
}
""");

        var taskGraphService = new TaskGraphService(new InMemoryTaskGraphRepository(new DomainTaskGraph()), new ApplicationTaskScheduler());
        var builder = new FileCodeGraphBuilder(workspace.RootPath, workspace.Paths, TestSystemConfigFactory.Create());
        var queryService = new FileCodeGraphQueryService(workspace.Paths, builder);
        var planner = new PlannerService(new CardParser(), new TaskDecomposer(), new StubGitClient(), taskGraphService, builder, queryService);

        var tasks = planner.PlanCard(cardPath, TestSystemConfigFactory.Create());

        Assert.All(tasks, task => Assert.Equal("Sample.Consumer", task.Metadata["codegraph_impacted_modules"]));
        Assert.All(tasks, task => Assert.Contains("Dependent module: Sample.Consumer", task.Metadata["codegraph_impact_summary"], StringComparison.Ordinal));
    }

    [Fact]
    public void Build_ExcludesGeneratedArtifactsFromCodeGraphTruth()
    {
        using var workspace = new TemporaryWorkspace();
        workspace.WriteFile("src/Sample.Module/OrderService.cs", """
namespace Sample.Module;

public sealed class OrderService
{
    public void PlanOrder()
    {
    }
}
""");
        workspace.WriteFile("src/Sample.Module/obj/project.assets.json", """
{ "version": 3 }
""");
        workspace.WriteFile("src/Sample.Module/bin/Debug/net10.0/Sample.Module.deps.json", """
{ "runtimeTarget": { "name": ".NETCoreApp,Version=v10.0" } }
""");
        workspace.WriteFile("src/Sample.Module/obj/Debug/net10.0/Sample.Module.GlobalUsings.g.cs", """
// <auto-generated/>
global using System;
""");
        workspace.WriteFile("tests/Sample.Module.Tests/OrderServiceTests.cs", """
namespace Sample.Module.Tests;

public sealed class OrderServiceTests
{
    public void CoversOrder()
    {
    }
}
""");
        workspace.WriteFile("tests/Sample.Module.Tests/obj/project.assets.json", """
{ "version": 3 }
""");

        var builder = new FileCodeGraphBuilder(workspace.RootPath, workspace.Paths, TestSystemConfigFactory.Create(["src", "tests"]));
        var result = builder.Build();
        var indexedPaths = result.Index.Files.Select(file => file.Path).ToArray();

        Assert.Contains("src/Sample.Module/OrderService.cs", indexedPaths);
        Assert.Contains("tests/Sample.Module.Tests/OrderServiceTests.cs", indexedPaths);
        Assert.DoesNotContain(indexedPaths, path => path.Contains("/obj/", StringComparison.OrdinalIgnoreCase));
        Assert.DoesNotContain(indexedPaths, path => path.Contains("/bin/", StringComparison.OrdinalIgnoreCase));
        Assert.DoesNotContain(indexedPaths, path => path.EndsWith(".deps.json", StringComparison.OrdinalIgnoreCase));
        Assert.DoesNotContain(indexedPaths, path => path.EndsWith(".GlobalUsings.g.cs", StringComparison.OrdinalIgnoreCase));
        Assert.DoesNotContain(indexedPaths, path => path.EndsWith("project.assets.json", StringComparison.OrdinalIgnoreCase));
    }

    [Fact]
    public void QueryService_LoadsLayeredCodeGraphArtifactsWithoutLegacyRootIndex()
    {
        using var workspace = new TemporaryWorkspace();
        workspace.WriteFile("src/Sample.Module/OrderService.cs", """
namespace Sample.Module;

public sealed class OrderService
{
    public void PlanOrder()
    {
    }
}
""");
        workspace.WriteFile("src/Sample.Consumer/OrderConsumer.cs", """
using Sample.Module;

namespace Sample.Consumer;

public sealed class OrderConsumer
{
    public void Consume(OrderService service)
    {
    }
}
""");

        var builder = new FileCodeGraphBuilder(workspace.RootPath, workspace.Paths, TestSystemConfigFactory.Create());
        var queryService = new FileCodeGraphQueryService(workspace.Paths, builder);
        builder.Build();

        var manifestPath = Path.Combine(workspace.RootPath, ".ai", "codegraph", "manifest.json");
        var searchIndexPath = Path.Combine(workspace.RootPath, ".ai", "codegraph", "search", "index.json");
        var moduleShardPath = Path.Combine(workspace.RootPath, ".ai", "codegraph", "modules", "Sample.Module.json");
        var legacyIndexPath = Path.Combine(workspace.RootPath, ".ai", "codegraph", "index.json");
        File.Delete(legacyIndexPath);

        var manifest = queryService.LoadManifest();
        var modules = queryService.LoadModuleSummaries();
        var rebuiltIndex = queryService.LoadIndex();
        var scope = queryService.AnalyzeScope(["src/Sample.Module/"]);

        Assert.True(File.Exists(manifestPath));
        Assert.True(File.Exists(searchIndexPath));
        Assert.True(File.Exists(moduleShardPath));
        Assert.Equal(2, manifest.ModuleCount);
        Assert.Contains(modules, module => string.Equals(module.Name, "Sample.Module", StringComparison.Ordinal));
        Assert.Contains(rebuiltIndex.Callables, callable => callable.QualifiedName.EndsWith(".PlanOrder", StringComparison.Ordinal));
        Assert.Contains(scope.Callables, callable => callable.EndsWith(".PlanOrder", StringComparison.Ordinal));
    }
}
