namespace Carves.Runtime.Application.ControlPlane;

internal static partial class OperatorTaskFormatter
{
    public static IReadOnlyList<string> HelpLines()
    {
        return
        [
            "Available commands:",
            "(no command)",
            "status",
            "status --runs",
            "verify runtime",
            "plan-card <card-path> [--persist]",
            "approve-task <task-id>",
            "approve-review <task-id> [--provisional] <reason...>",
            "reject-review <task-id> <reason...>",
            "reopen-review <task-id> <reason...>",
            "review block <task-id> <reason...>",
            "review supersede <task-id> <reason...>",
            "run <repo-path> [--dry-run]",
            "host start [--port <port>] [--interval-ms <milliseconds>]",
            "host ensure [--json]   # safe validation/start; does not replace stale conflicting generations",
            "host reconcile [--replace-stale] [--json]",
            "host reconcile --replace-stale [--json]   # explicit destructive replacement for host_session_conflict only",
            "host status [--require-capability <capability>]",
            "host pause <reason...>",
            "host resume [reason...]",
            "host stop <reason...>",
            "host [--dry-run] [--cycles <count>] [--interval-ms <milliseconds>] [--slots <count>]",
            "console [--script <steps>]",
            "attach [repo-path] [--repo-id <id>] [--provider-profile <profile>] [--policy-profile <profile>] [--start-runtime] [--dry-run] [--force]",
            "repair",
            "rebuild",
            "reset --derived",
            "compact-history",
            "audit sustainability",
            "inspect sustainability",
            "inspect history-compaction",
            "inspect archive-readiness",
            "inspect archive-followup",
            "inspect execution-run-exceptions",
            "create-card-draft <json-path> [--repo-id <id>]",
            "update-card <card-id> <json-path> [--repo-id <id>]",
            "list-cards [--state <state>] [--repo-id <id>]",
            "inspect-card <card-id> [--repo-id <id>]",
            "approve-card <card-id> [reason...] [--repo-id <id>]",
            "reject-card <card-id> [reason...] [--repo-id <id>]",
            "archive-card <card-id> [reason...] [--repo-id <id>]",
            "supersede-card-tasks <card-id> <reason...> [--repo-id <id>]",
            "create-taskgraph-draft <json-path>",
            "approve-taskgraph-draft <draft-id> [reason...]",
            "inspect <card|task|run|execution-trace|attach-proof|pilot-evidence|methodology> <id>",
            "inspect <card-draft|taskgraph-draft|replan|suggested-tasks|execution-memory> <id>",
            "inspect <sustainability|history-compaction|archive-readiness|archive-followup|execution-run-exceptions>",
            .. RuntimeSurfaceCommandRegistry.BuildHelpLines("inspect"),
            "inspect async-resume-gate",
            "inspect dispatch runtime",
            "pilot start [--json]",
            "pilot next [--json]",
            "pilot problem-intake [--json]",
            "pilot triage [--json]",
            "pilot problem-triage [--json]",
            "pilot friction-ledger [--json]",
            "pilot follow-up [--json]",
            "pilot problem-follow-up [--json]",
            "pilot triage-follow-up [--json]",
            "pilot follow-up-plan [--json]",
            "pilot problem-follow-up-plan [--json]",
            "pilot triage-follow-up-plan [--json]",
            "pilot follow-up-record [--json]",
            "pilot follow-up-decision-record [--json]",
            "pilot problem-follow-up-record [--json]",
            "pilot follow-up-intake [--json]",
            "pilot follow-up-planning [--json]",
            "pilot problem-follow-up-intake [--json]",
            "pilot follow-up-gate [--json]",
            "pilot follow-up-planning-gate [--json]",
            "pilot problem-follow-up-gate [--json]",
            "pilot record-follow-up-decision <decision> [--all] [--candidate <candidate-id>...] --reason <text>",
            "pilot report-problem <json-path> [--json]",
            "pilot list-problems [--repo-id <id>]",
            "pilot inspect-problem <problem-id>",
            "pilot close-loop <task-id> [--record-evidence <json-path>]",
            "pilot record-evidence <json-path>",
            "pilot list-evidence [--repo-id <id>]",
            "pilot inspect-evidence <evidence-id>",
            "run-next [--dry-run]",
            "run task <task-id> [--dry-run]",
            "review task <task-id> <verdict> <reason...>",
            "review-task <task-id> <verdict> <reason...>",
            "session start [--dry-run]",
            "session status",
            "session tick [--dry-run]",
            "session loop [--dry-run] [--iterations <count>]",
            "session pause <reason...>",
            "session resume <reason...>",
            "session stop <reason...>",
            "planner status",
            "planner run [--dry-run] [--wake <reason>] [--detail <text>]",
            "planner host [--dry-run] [--iterations <count>]",
            "planner wake <reason> <detail...>",
            "planner sleep <reason> <detail...>",
            "show-graph",
            "show-backlog",
            "detect-opportunities",
            "show-opportunities",
            "hosts",
            "fleet status [--full]",
            "repo list",
            "repo register <repo-path> [--repo-id <id>] [--provider-profile <profile>] [--policy-profile <profile>]",
            "repo inspect <repo-id>",
            "runtime list",
            "runtime inspect <repo-id>",
            "runtime start <repo-id> [--dry-run]",
            "runtime resume <repo-id> <reason...>",
            "runtime pause <repo-id> <reason...>",
            "runtime stop <repo-id> <reason...>",
            "runtime schedule [--slots <count>]",
            "runtime admit-pack <pack-artifact-path> --attribution <runtime-pack-attribution-path>",
            "runtime admit-pack-v1 <runtime-pack-v1-manifest-path> [--channel <channel>] [--published-by <principal>] [--source-line <line>]",
            "runtime assign-pack <pack-id> [--pack-version <version>] [--channel <channel>] [--reason <text>]",
            "runtime rollback-pack <selection-id> [--reason <text>]",
            "runtime pin-current-pack [--reason <text>]",
            "runtime clear-pack-pin [--reason <text>]",
            "runtime export-pack-policy <output-path>",
            "runtime preview-pack-policy <input-path>",
            "runtime import-pack-policy <input-path>",
            "pack validate <json-path>",
            "pack admit <runtime-pack-v1-manifest-path> [--channel <channel>] [--published-by <principal>] [--source-line <line>]",
            "pack assign <pack-id> [--pack-version <version>] [--channel <channel>] [--reason <text>]",
            "pack pin [--reason <text>]",
            "pack unpin [--reason <text>]",
            "pack rollback <selection-id> [--reason <text>]",
            "pack inspect <admission|admission-policy|selection|switch-policy|policy-audit|policy-preview|policy-transfer|distribution-boundary>",
            "pack explain --task <task-id>",
            "pack audit",
            "pack mismatch",
            "provider list",
            "provider inspect <provider-id>",
            "provider bind <repo-id> <profile-id>",
            "provider quota",
            "provider route <repo-id> <role> [--no-fallback]",
            "policy inspect",
            "policy validate",
            "validate card <card-path> [--strict]",
            "validate task <task-path>",
            "validate safety --actor <planner|worker|operator> --op <read|write|delete|execute> [--path <target-path>] [<target-path> ...]",
            "validate memory <memory-meta-path> [--strict]",
            "validate pack-artifact <json-path>",
            "validate runtime-pack-v1 <json-path>",
            "validate runtime-pack-attribution <json-path>",
            "validate runtime-pack-policy-package <json-path>",
            "governance show",
            "governance inspect <repo-id>",
            "worker list",
            "worker providers",
            "worker profiles [repo-id]",
            "worker select <repo-id> [--task-id <task-id>]",
            "worker health [--backend <backend-id>] [--no-refresh]",
            "worker policy [repo-id]",
            "worker activate-external-app-cli [--dry-run] [--reason <text>]",
            "worker activate-external-codex [--dry-run] [--reason <text>]",
            "worker approvals",
            "worker approve <permission-request-id> [actor-identity]",
            "worker deny <permission-request-id> [actor-identity]",
            "worker timeout <permission-request-id> [actor-identity]",
            "worker audit [--task-id <task-id>] [--request-id <permission-request-id>]",
            "worker incidents [--task-id <task-id>] [--run-id <run-id>]",
            "worker leases",
            "worker heartbeat <node-id>",
            "worker quarantine <node-id> <reason...>",
            "worker expire <lease-id> <reason...>",
            "worker supervisor-launch --identity <id> [--repo-id <id>] [--worker-instance-id <id>] [--actor-session-id <id>] [--provider-profile <id>] [--capability-profile <id>] [--schedule-binding <id>] [--reason <text>] [--dry-run]",
            "worker supervisor-instances [--repo-id <id>]",
            "worker supervisor-events [--repo-id <id>] [--worker-instance-id <id>] [--actor-session-id <id>]",
            "worker supervisor-archive --worker-instance-id <id> [--reason <text>] [--dry-run]",
            "actor sessions [--kind <operator|agent|planner|worker>] [--repo-id <id>]",
            "actor register --kind <operator|agent|planner|worker> --identity <id> [--repo-id <id>] [--actor-session-id <id>] [--provider-profile <id>] [--capability-profile <id>] [--scope <scope>] [--budget-profile <id>] [--schedule-binding <id>] [--context-receipt <id>] [--health <posture>] [--process-id <pid>] [--registration-mode <manual|supervised>] [--worker-instance-id <id>] [--launch-token <token>] [--reason <text>] [--dry-run]",
            "actor ownership [--scope <scope>] [--target-id <id>]",
            "actor events [--task-id <task-id>] [--actor-session-id <id>] [--kind <event-kind>]",
            "actor repair-sessions [--dry-run]",
            "api platform-status",
            "api repos",
            "api repo-runtime <repo-id>",
            "api repo-tasks <repo-id>",
            "api repo-opportunities <repo-id>",
            "api repo-session <repo-id>",
            "api provider-quota",
            "api provider-route <repo-id> <role> [--no-fallback]",
            "api platform-schedule [--slots <count>]",
            "api worker-providers",
            "api worker-profiles [repo-id]",
            "api worker-selection <repo-id> [--task-id <task-id>]",
            "api worker-health [--backend <backend-id>] [--no-refresh]",
            "api worker-automation-readiness [--repo-id <repo-id>] [--refresh-worker-health]",
            "api worker-automation-schedule-tick [--repo-id <repo-id>] [--refresh-worker-health] [--dispatch] [--execute]",
            "api worker-supervisor-launch --identity <id> [--repo-id <id>] [--worker-instance-id <id>] [--actor-session-id <id>] [--provider-profile <id>] [--capability-profile <id>] [--schedule-binding <id>] [--reason <text>] [--dry-run]",
            "api worker-supervisor-instances [--repo-id <id>]",
            "api worker-supervisor-events [--repo-id <id>] [--worker-instance-id <id>] [--actor-session-id <id>]",
            "api worker-supervisor-archive --worker-instance-id <id> [--reason <text>] [--dry-run]",
            "api worker-external-app-cli-activation [--dry-run] [--reason <text>]",
            "api worker-external-codex-activation [--dry-run] [--reason <text>]",
            "api worker-permissions",
            "api worker-permission-audit [--task-id <task-id>] [--request-id <permission-request-id>]",
            "api worker-incidents [--task-id <task-id>] [--run-id <run-id>]",
            "api worker-leases",
            "api actor-sessions [--kind <operator|agent|planner|worker>] [--repo-id <id>]",
            "api actor-session-register --kind <operator|agent|planner|worker> --identity <id> [--repo-id <id>] [--actor-session-id <id>] [--provider-profile <id>] [--capability-profile <id>] [--scope <scope>] [--budget-profile <id>] [--schedule-binding <id>] [--context-receipt <id>] [--health <posture>] [--process-id <pid>] [--registration-mode <manual|supervised>] [--worker-instance-id <id>] [--launch-token <token>] [--reason <text>] [--dry-run]",
            "api actor-session-repair [--dry-run]",
            "api actor-session-stop --actor-session-id <id> [--reason <text>] [--dry-run]",
            "api actor-session-heartbeat --actor-session-id <id> [--health <posture>] [--context-receipt <id>] [--reason <text>] [--dry-run]",
            "api actor-ownership [--scope <scope>] [--target-id <id>]",
            "api os-events [--task-id <task-id>] [--actor-session-id <id>] [--kind <event-kind>]",
            .. RuntimeSurfaceCommandRegistry.BuildHelpLines("api"),
            "api repo-gateway <repo-id>",
            "dashboard [repo-id]",
            "dashboard --text",
            "intent status",
            "intent draft [--persist]",
            "intent focus <candidate-card-id|none|clear>",
            "intent decision <decision-id> <open|resolved|paused|forbidden>",
            "intent candidate <candidate-card-id> <emerging|needs_confirmation|wobbling|grounded|paused|forbidden|ready_to_plan>",
            "intent accept",
            "intent discard",
            "protocol status",
            "protocol check <phase>",
            "prompt kernel",
            "prompt templates",
            "prompt template <id>",
            "card create-draft <json-path> [--repo-id <id>]",
            "card list [--state <state>] [--repo-id <id>]",
            "card inspect <card-id> [--repo-id <id>]",
            "card update <card-id> <json-path> [--repo-id <id>]",
            "card status <card-id> <draft|reviewed|approved|rejected|archived> [reason...] [--repo-id <id>]",
            "task inspect <task-id> [--runs]",
            "task run <task-id> [--dry-run]",
            "task retry <task-id> <reason...>",
            "discuss context",
            "discuss brief-preview",
            "discuss planner",
            "discuss blocked",
            "discuss card <card-id>",
            "discuss task <task-id>",
            "agent context [<task-id>] [--json]",
            "agent <query|request|report> <operation> [target-id]",
            "lint-platform",
            "safety-check",
            "scan-code",
            "detect-refactors",
            "materialize-refactors",
            "sync-state",
            "explain-task <task-id>",
        ];
    }
}
