using Carves.Runtime.Application.AI;
using Carves.Runtime.Application.Artifacts;
using Carves.Runtime.Application.CodeGraph;
using Carves.Runtime.Application.Configuration;
using Carves.Runtime.Application.Failures;
using Carves.Runtime.Application.Git;
using Carves.Runtime.Application.Interaction;
using Carves.Runtime.Application.Orchestration;
using Carves.Runtime.Application.Persistence;
using Carves.Runtime.Application.Platform;
using Carves.Runtime.Application.Planning;
using Carves.Runtime.Application.Refactoring;
using Carves.Runtime.Application.Safety;
using Carves.Runtime.Application.TaskGraph;

namespace Carves.Runtime.Application.ControlPlane;

public sealed partial class OperatorSurfaceService
{
    private readonly string repoRoot;
    private readonly ControlPlanePaths paths;
    private readonly SystemConfig systemConfig;
    private readonly AiProviderConfig aiProviderConfig;
    private readonly IAiClient aiClient;
    private readonly IGitClient gitClient;
    private readonly IControlPlaneLockService controlPlaneLockService;
    private readonly IControlPlaneConfigRepository configRepository;
    private readonly TaskGraphService taskGraphService;
    private readonly PlannerService plannerService;
    private readonly DevLoopService devLoopService;
    private readonly IMarkdownSyncService markdownSyncService;
    private readonly ICodeGraphBuilder codeGraphBuilder;
    private readonly ICodeGraphQueryService codeGraphQueryService;
    private readonly IRefactoringService refactoringService;
    private readonly SafetyService safetyService;
    private readonly IRuntimeArtifactRepository artifactRepository;
    private readonly PlannerReviewArtifactFactory reviewArtifactFactory;
    private readonly ReviewWritebackService reviewWritebackService;
    private readonly ReviewEvidenceGateService reviewEvidenceGateService;
    private readonly RuntimeFailurePolicy runtimeFailurePolicy;
    private readonly FailureReportService failureReportService;
    private readonly FailureContextService failureContextService;
    private readonly FailureSummaryService failureSummaryService;
    private readonly PlannerTriggerService plannerTriggerService;
    private readonly DispatchProjectionService dispatchProjectionService;
    private readonly ExecutionRunService executionRunService;
    private readonly ResultIngestionService resultIngestionService;
    private readonly OpportunityDetectorService opportunityDetectorService;
    private readonly RepoRegistryService repoRegistryService;
    private readonly RepoRuntimeService repoRuntimeService;
    private readonly RuntimeInstanceManager runtimeInstanceManager;
    private readonly ProviderRegistryService providerRegistryService;
    private readonly ProviderRoutingService providerRoutingService;
    private readonly PlatformGovernanceService platformGovernanceService;
    private readonly PlatformSchedulerService platformSchedulerService;
    private readonly ActorSessionService actorSessionService;
    private readonly SessionOwnershipService sessionOwnershipService;
    private readonly ConcurrentActorArbitrationService concurrentActorArbitrationService;
    private readonly OperatorOsEventStreamService operatorOsEventStreamService;
    private readonly PlatformVocabularyLintService platformVocabularyLintService;
    private readonly OperatorApiService operatorApiService;
    private readonly PlatformDashboardService platformDashboardService;
    private readonly RuntimeConsistencyCheckService runtimeConsistencyCheckService;
    private readonly DelegatedWorkerLifecycleReconciliationService delegatedWorkerLifecycleReconciliationService;
    private readonly OperationalSummaryService operationalSummaryService;
    private readonly GovernanceReportingService governanceReportingService;
    private readonly DelegationReportingService delegationReportingService;
    private readonly WorktreeResourceCleanupService worktreeResourceCleanupService;
    private readonly Carves.Runtime.Application.Workers.WorkerBroker workerBroker;
    private readonly InteractionLayerService interactionLayerService;
    private readonly Carves.Runtime.Application.Workers.WorkerExecutionBoundaryService workerExecutionBoundaryService;
    private readonly Carves.Runtime.Application.Workers.WorkerSelectionPolicyService workerSelectionPolicyService;
    private readonly Carves.Runtime.Application.Workers.ApprovalPolicyEngine approvalPolicyEngine;
    private readonly Carves.Runtime.Application.Workers.WorkerPermissionOrchestrationService workerPermissionOrchestrationService;
    private readonly Carves.Runtime.Application.Workers.IWorkerExecutionAuditReadModel? workerExecutionAuditReadModel;
    private readonly RuntimePolicyBundleService runtimePolicyBundleService;
    private readonly HostRegistryService hostRegistryService;
    private readonly PlanningDraftService planningDraftService;
    private readonly ManagedWorkspaceLeaseService managedWorkspaceLeaseService;
    private readonly ContextPackService contextPackService;
    private readonly CurrentModelQualificationService currentModelQualificationService;
    private readonly RoutingValidationService routingValidationService;
    private readonly RoutingPromotionDecisionService routingPromotionDecisionService;
    private readonly ValidationCoverageMatrixService validationCoverageMatrixService;
    private readonly RoutingCandidateReadinessService routingCandidateReadinessService;
    private readonly SpecificationValidationService specificationValidationService;
    private readonly ExecutionPacketCompilerService executionPacketCompilerService;
}
